site_name: TIL@scarf
repo_url: https://github.com/scarf005/TIL/

theme:
  name: material
  language: kr

  font:
    code: Ubuntu Mono

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - header.autohide

plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Seoul

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra:
  generator: false # hides footer

extra_css:
  - stylesheets/extra.css
