site_name: TIL@scarf
repo_url: https://github.com/scarf005/TIL/

theme:
  name: material
  language: kr
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

plugins:
  - tags:
      tags_file: tags.md
